version: '3'

networks:
  default:
    external:
      name: nginx-proxy
  internal:
    internal: true
volumes:
  dbdatsedu:

services:
  # php-apache server configuration
  php-edu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-edu
    ports:
      - 8090:80
    depends_on:
      - mysqlbdedu
    restart: always
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL:
# mysql configuration
  mysqlbdedu:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "9002:3306"
    volumes:
    # Montamos un volumen para el MySQL para no perder los datos de bd
    - dbdatsedu:/var/lib/mysql

# phpmyadmin configuration
  phpmyadminedu:
    container_name: phpmyadminedu
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8093
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 512M
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      VIRTUAL_HOST: dbeducalma.${MAIN_URL}
      LETSENCRYPT_HOST: dbeducalma.${MAIN_URL}
      LETSENCRYPT_EMAIL:

